## 2010-2019 kospi200 편입여부 확인

In [2]:
import numpy as np
import pandas as pd
import re

In [3]:
df = pd.read_csv('./data/crawling/preprocessed/Lv.1_dongchan.csv',encoding='euc-kr',index_col=0)
df = df.drop(['str_tokens','url'],axis=1)
df_boolean = pd.read_csv('./data/kospi/raw/KOSPI200_편입여부1.csv',low_memory=False)

In [4]:
df.head()

,crp_nm,crp_cd,연도,rpt_nm,rcp_no,rcp_dt,rmk,str
0,AK홀딩스,6840,2018,사업보고서 (2018.12),20190401004433,20190401,연,IV. 이사의 경영진단 및 분석의견1. 예측정보에 대한 주의사항당사가 동 사업보고서...
1,AK홀딩스,6840,2017,사업보고서 (2017.12),20180330002417,20180330,연,V. 이사의 경영진단 및 분석의견1. 예측정보에 대한 주의사항당사가 동 사업보고서에...
2,AK홀딩스,6840,2016,사업보고서 (2016.12),20170331003282,20170331,연,V. 이사의 경영진단 및 분석의견1. 예측정보에 대한 주의사항당사가 동 사업보고서에...
3,AK홀딩스,6840,2015,사업보고서 (2015.12),20160330003602,20160330,연,V. 이사의 경영진단 및 분석의견1. 예측정보에 대한 주의사항당사가 동 사업보고서에...
4,AK홀딩스,6840,2014,사업보고서 (2014.12),20150331003839,20150331,정연,V. 이사의 경영진단 및 분석의견1. 예측정보에 대한 주의사항당사가 동 사업보고서에...

In [5]:
df.str[0]

"IV. 이사의 경영진단 및 분석의견1. 예측정보에 대한 주의사항당사가 동 사업보고서에서 미래에 발생할 것으로 예상,예측한 활동, 사건 또는 현상은 당해 공시서류 작성시점의 사건 및 재무성과에 대하여 회사의 견해를 반영한 것입니다. 동 예측정보는 미래 사업환경과 관련된 다양한 가정에 기초하고 있으며, 동 가정들은 결과적으로 부정확한 것으로 판명될 수도 있습니다. 또한, 이러한 가정들에는예측정보에서 기재한 예상치와 실제 결과 간에 중요한 차이를 초래할 수 있는 위험, 불확실성 및 기타요인을 포함하고 있습니다. 이러한 중요한 차이를 초래할 수 있는 요인에는 회사 내부경영과 관련된 요인과 외부환경에 관한 요인이 포함되어 있으며, 이에 한하지 않습니다.당사는 동 예측정보 작성시점 이후에 발생하는 위험 또는 불확실성을 반영하기 위하여 예측정보에 기재한 사항을 수정하는 정정보고서를 공시할 의무는 없습니다. 결론적으로, 동 사업보고서상에 회사가 예상한 결과 또는 사항이 실현되거나 회사가 당초에 예상한 영향이 발생한다는 확신을 제공할 수 없습니다. 동 보고서에 기재된 예측정보는 동 보고서 작성시점을 기준으로 작성한 것이며, 회사가 이러한 위험요인이나예측정보를 업데이트할 예정이 없음을 유의하시기 바랍니다.2. 개요최근 국내외의 여러 불안 요소들로 모두가 위축된 경제 활동을 할 수 밖에 없는 상황에도, 국내 기업들은 내실을 다지면서 신규 시장 개척에 매진하는 등 어려운 시기를 훌륭히 극복하여 왔습니다. 그러나 계속되는 경기 침체와 저성장 환경이 기업에게 개혁과 변화를 계속 요구하고 있어, 당사는 기업 지배구조의 투명성을 증대시켜 시장에서의 기업가치를 최대화하고, 당사가 투자하고 있는 관계회사들마다 신속하고 전문화 된 의사결정이 가능한 지배구조 체제를 확립하여 각 사업부문에 역량을 집중시키는 것을 목적으로, 2012년 9월 1일 애경유화(주)를 인적 분할하여 분할존속법인인 당사는 애경유화(주)에서 에이케이홀딩스(주)로 상호를 변경하고  2012년 9월 17일 한국거래소 유가증권시장에 변경상장 하였습니다. 또한 분할로 신설된 법인인 애경유화(주)는 분할되는 회사(당사)가 영위하던 화학제조판매 사업부문을 영위하게 되며, 재상장 심사를 거쳐 한국거래소 유가증권시장에 2012년 9월 17일 재상장 되었습니다.2018년말 현재, 한국채택국제회계기준의 도입에 따른 주요 연결종속회사들이 영위하는 사업으로는 화학부문(애경유화, 에이케이켐텍), 생활항공부문(제주항공,애경산업), 유통부동산부문(에이케이에스앤디)이 있습니다. 이외에도 연결대상 종속회사는 아니지만, 주요 자회사로 분류되는 애경화학(화학부문), 에이엠플러스자산개발(유통부동산부문)이 있습니다.당사는 지주회사로서 2019년에도 성장 기반 마련을 위한 지주회사 체제 구축에 중점을 둔 경영을 하고자 합니다. 또한 빠르게 변화하는 경영환경에 유연하게 대처하고 재무안정성 및 경영활동에 대한 리스크 관리에 힘씀과 더불어, 각 사업별 책임경영 및 전문화를 통해 자회사가 핵심 사업에 집중할 수 있도록 하여 자회사의 역량을 최대한으로 이끌어 낼 것이며, 나아가 신성장 동력을 확대할 수 있도록 미래성장 사업에 대한 투자 및 사업구조 고도화에 집중토록 함으로서 중장기적 기업가치 제고에 전력을 경주해 나갈 것입니다.3. 재무상태 및 영업실적(연결기준)&lt;당사 및 연결대상 종속회사&gt;가. 재무상태(연결기준)\r※제48기(전기) 재무정보는 K-IFRS 1018호, 1039호 등 종전기준서에 따라 작성되었습니다.연결실체의 2018년말 총 자산은 전년대비 15% 증가한 3조 3,979억원 이고, 자산이 증가한 주요 원인은 당기 연결종속회사들의 투자활동으로 인해 유형자산이 2,930억 증가했기 때문입니다. 총 부채는 전년대비 7% 증가한 1조 9,240억원 입니다.나. 영업실적(연결기준)※제48기(전기) 재무정보는 K-IFRS 1018호, 1039호 등 종전기준서에 따라 작성되었습니다.연결실체의 당기 매출은 전년대비 9% 증가한 3조 7,112억원, 영업이익은 전년대비 2% 증가한 2,697억원, 당기순이익은 전년대비 11% 증가한 2,066억원을 기록하였습니다. 다. 연결대상 종속기업 관련 재무정보 요약연결대상 종속기업의 보고기간종료일 현재 요약재무상태표와 당기 및 전기 요약포괄손익계산서는 다음과 같습니다.(2) 주요 자회사의 영업실적, 재무상태의 변동 등 향후 사업예측에 필요한 부문별 정보는 사업보고서 본문 II. 사업의 내용을 참조하시기 바랍니다.라. 재무비율(연결기준)당기 이자보상배율은 9.7배로 전기 9.3배 대비 0.4 개선되었습니다.4. 유동성 및 자금조달과 지출가. 유동성(연결기준)\r연결실체는 2018년 영업활동으로 3,173억원 유입되었으며, 투자활동 및 재무활동으로 각각 2,246억원 유출, 900억원이 유입되었습니다. 전년대비 현금이 1,826억원 증가하여, 당기말 현재 현금 및 현금성 자산은 5,114억원을 보유하고 있습니다.나. 자금조달(연결기준)연결실체의 총차입금 7,404억원 중 단기차입금은 4,538억원이며, 구성비율은 61% 입니다.(1) 단기차입금의 내역은 다음과 같습니다.(*) 보고기간종료일 현재 금융기관 등에 양도한 매출채권 중 담보부차입으로 회계처리한 금액입니다.(2) 장기차입금의 내역은 다음과 같습니다.연결기업은 신용카드 매출채권 신탁을 통한 자산 유동화대출과 관련하여 에이케이원주제이차유한회사, 에이케이수원제오차유한회사, 그리고 에이케이수원제육차유한회사에 각 차입잔액 200억, 75억, 480억에 대한 연대보증 및 자금보충약정을 제공하고있으며 동 유동화 차입금이 연결기업의 재무제표에 차입금으로 계상되어 있으므로 추가적인 재무부담은 없습니다.\r5. 부외거래ⅩI. 그 밖에 투자자 보호를 위하여 필요한 사항의 '2.우발채무 등'을 참고하시기 바랍니다.6. 그 밖에 투자의사결정에 필요한 사항가. 중요한 회계정책 및 추정에 관한 사항 첨부된 연결감사보고서의 연결재무제표에 대한 주석 '2.3 중요한 회계정책', '3. 중요한 회계적 판단, 추정 및 가정'을 참고하시기 바랍니다.나. 파생상품 및 위험관리정책에 관한 사항Ⅱ. 사업의 내용의 '재무위험관리', '파생상품 계약 현황'을 참고하시기 바랍니다.\r"

In [6]:
def length_adjust(str_) : 
    return (2-len(str_)) * '0' + str_

def date_convertor(date) : 
    year = length_adjust(str(date.year))
    month = length_adjust(str(date.month))
    day = length_adjust(str(date.day))
    yyyymmdd = int(year+month+day)
    return yyyymmdd

In [7]:
dts = df_boolean.iloc[1:,0] #datetime형식을 통일시켜준다
dates_str = []
for idx,i in enumerate(dts):
    i = df_boolean.iloc[idx+1,0][0:4]+df_boolean.iloc[idx+1,0][5:7]+df_boolean.iloc[idx+1,0][8:10] 
    dates_str.append(i)

dates_str.insert(0,'Symbol Name')


symbol_ls = [x for x in df_boolean.columns][1:]
crp_ls = []
for i in symbol_ls:
    if df_boolean[i][1:].isin(['Y']).all() == True:   #전체 kospi기업에서 10년동안 kospi200에 편입되었던 기업들만 추출
        crp_ls.append(i)


dts = df_boolean.iloc[1:,0] #datetime형식을 통일시켜준다
dates_str = []
for idx,i in enumerate(dts):
    i = df_boolean.iloc[idx+1,0][0:4]+df_boolean.iloc[idx+1,0][5:7]+df_boolean.iloc[idx+1,0][8:10] 
    dates_str.append(i)

dates_str.insert(0,'Symbol Name')

df_boolean = df_boolean.loc[:,crp_ls]
df_boolean.index = dates_str

In [8]:
df_boolean.head()

,A000070,A000100,A000120,A000150,A000210,A000240,A000270,A000640,A000660,A000670,...,A069960,A071050,A078930,A086790,A090430,A093050,A093370,A096770,A097950,A105560
Symbol Name,삼양홀딩스,유한양행,CJ대한통운,두산,대림산업,한국테크놀로지그룹,기아차,동아쏘시오홀딩스,SK하이닉스,영풍,...,현대백화점,한국금융지주,GS,하나금융지주,아모레퍼시픽,LF,후성,SK이노베이션,CJ제일제당,KB금융
20100101,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y
20100102,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y
20100103,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y
20100104,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y

## kospi200 기업의 일별 종가 추출

FinanceDataReader 패키지를 이용하여 2010년부터 2019년 말까지 해당 기업의 종가를 가져오는 함수를 구현한다. 개별기업의 주가를 dataframe형식으로 반환하므로 10년동안 지수에 편입되었던 113개의 기업들에 대하여 수정종가, 수익률 , 그리고 naive하게 market return을 제외한 수익률을 구하였다.

In [9]:
def close_price(code): #개별기업코드 입력시 종가 반환
    
    import FinanceDataReader as fdr
    
    df = fdr.DataReader(code, start = '2010-01-01' , end = '2019-12-31')
    df = df['Close']
    
    return df

In [10]:
def get_return(code): #개별기업코드 입력시 수익률 반환
    
    import FinanceDataReader as fdr
    
    df = fdr.DataReader(code, start = '2010-01-01' , end = '2019-12-31')
    df = df['Change']
    
    return df

In [11]:
df_boolean

,A000070,A000100,A000120,A000150,A000210,A000240,A000270,A000640,A000660,A000670,...,A069960,A071050,A078930,A086790,A090430,A093050,A093370,A096770,A097950,A105560
Symbol Name,삼양홀딩스,유한양행,CJ대한통운,두산,대림산업,한국테크놀로지그룹,기아차,동아쏘시오홀딩스,SK하이닉스,영풍,...,현대백화점,한국금융지주,GS,하나금융지주,아모레퍼시픽,LF,후성,SK이노베이션,CJ제일제당,KB금융
20100101,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y
20100102,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y
20100103,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y
20100104,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20191227,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y
20191228,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y
20191229,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y
20191230,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y
20191231,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y

In [12]:
symbols = [x for x in df_boolean.iloc[0,:]] #기업명 리스트
t_ls = [x[1:] for x in df_boolean.columns] #종목코드
symbol_dic = {name:value for name,value in zip(symbols,t_ls)}


close_ls = [close_price(x) for x in t_ls] 
return_ls = [get_return(x) for x in t_ls]

df__price = pd.concat([i for i in close_ls],ignore_index=False, axis =1)
df__price.columns = symbols
# df__price = df__price.fillna(int(0)) #str to int.. NaN값은0으로 변환

df_return = pd.concat([i for i in return_ls],ignore_index=False, axis =1)
df_return.columns = symbols
# df_return = df_return.fillna(int(0)) #str to int.. NaN값은0으로 변환


#datetime string으로 변환
dates = df__price.index
dates_ls = list(map(date_convertor,dates)) #datetime string으로 변환
df_price = df__price.copy()

df_price.index = dates_ls
df_return.index = dates_ls

In [13]:
df_return.shape
nan_mean  = np.nanmean(df_return, axis=1) #nan값빼고 market return을 naive하게 계산
demean = df_return.values-nan_mean.reshape(len(nan_mean),1) #market return 제외

df_demean= pd.DataFrame(demean,index=df_return.index, columns = df_return.columns)

In [14]:
df_price.head()

,삼양홀딩스,유한양행,CJ대한통운,두산,대림산업,한국테크놀로지그룹,기아차,동아쏘시오홀딩스,SK하이닉스,영풍,...,현대백화점,한국금융지주,GS,하나금융지주,아모레퍼시픽,LF,후성,SK이노베이션,CJ제일제당,KB금융
20100104,46517,28267,54500,74680,85300,12405,20800,97972,24100,569000,...,113000,34250,33750,33350,94224,31900,3726,117000,207000,59400
20100105,46257,28427,54400,74519,84500,11860,19650,94669,23350,550000,...,108000,34600,33900,33900,91524,30650,3702,121500,220000,58700
20100106,45894,28748,56400,78619,86200,11786,19850,92101,24550,537000,...,105500,34300,34250,33900,86022,30400,3755,122000,220500,58500
20100107,45167,28507,56600,80790,86000,11488,18950,92835,24400,535000,...,106000,33600,34600,33450,84122,30150,3785,121500,218000,57800
20100108,45063,28267,57600,86015,86900,11588,19350,92101,24650,533000,...,103500,35850,34450,33550,82821,30450,3804,122500,218000,57900

In [15]:
df_return

,삼양홀딩스,유한양행,CJ대한통운,두산,대림산업,한국테크놀로지그룹,기아차,동아쏘시오홀딩스,SK하이닉스,영풍,...,현대백화점,한국금융지주,GS,하나금융지주,아모레퍼시픽,LF,후성,SK이노베이션,CJ제일제당,KB금융
20100104,0.004492,-0.011228,-0.038801,-0.026209,0.025240,-0.017581,0.037406,0.038918,0.041037,0.000000,...,0.004444,0.022388,-0.001479,0.013678,0.008563,0.011094,-0.006665,-0.004255,0.007299,-0.005025
20100105,-0.005589,0.005660,-0.001835,-0.002156,-0.009379,-0.043934,-0.055288,-0.033714,-0.031120,-0.033392,...,-0.044248,0.010219,0.004444,0.016492,-0.028655,-0.039185,-0.006441,0.038462,0.062802,-0.011785
20100106,-0.007847,0.011292,0.036765,0.055020,0.020118,-0.006239,0.010178,-0.027126,0.051392,-0.023636,...,-0.023148,-0.008671,0.010324,0.000000,-0.060115,-0.008157,0.014317,0.004115,0.002273,-0.003407
20100107,-0.015841,-0.008383,0.003546,0.027614,-0.002320,-0.025284,-0.045340,0.007970,-0.006110,-0.003724,...,0.004739,-0.020408,0.010219,-0.013274,-0.022087,-0.008224,0.007989,-0.004098,-0.011338,-0.011966
20100108,-0.002303,-0.008419,0.017668,0.064674,0.010465,0.008705,0.021108,-0.007907,0.010246,-0.003738,...,-0.023585,0.066964,-0.004335,0.002990,-0.015466,0.009950,0.005020,0.008230,0.000000,0.001730
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20191223,0.009360,0.008283,-0.013029,0.007092,0.000000,-0.010417,0.001119,0.014085,-0.004211,-0.003185,...,-0.001212,0.006887,0.005703,0.003891,-0.024814,-0.002747,-0.027060,0.000000,0.008282,0.017329
20191224,0.015456,-0.006156,-0.009901,0.000000,-0.006550,0.000000,-0.001117,0.004630,-0.008457,0.020767,...,-0.008495,-0.001368,0.005671,-0.011628,0.007634,0.013774,0.013906,0.003257,-0.006160,-0.009018
20191226,0.012177,0.016532,0.000000,0.014085,-0.002198,0.014035,0.008949,0.004608,0.010661,-0.012520,...,0.001224,0.002740,0.000000,0.010458,-0.007576,0.013587,-0.006234,0.006494,0.004132,-0.001011
20191227,-0.003008,0.004246,0.030000,-0.023611,-0.022026,-0.020761,-0.016630,-0.022936,0.012658,-0.004754,...,-0.001222,-0.010929,-0.018797,-0.029754,-0.007634,-0.024129,0.017566,-0.025806,0.028807,-0.027328
20191230,0.010558,0.000000,0.003236,0.000000,0.019144,0.017668,-0.001127,0.009390,-0.019792,0.027070,...,0.017136,0.000000,-0.011494,-0.016000,0.025641,0.016484,0.007398,-0.006623,0.010000,-0.008325

In [16]:
df_demean.head()

,삼양홀딩스,유한양행,CJ대한통운,두산,대림산업,한국테크놀로지그룹,기아차,동아쏘시오홀딩스,SK하이닉스,영풍,...,현대백화점,한국금융지주,GS,하나금융지주,아모레퍼시픽,LF,후성,SK이노베이션,CJ제일제당,KB금융
20100104,-0.001326,-0.017046,-0.044618,-0.032027,0.019423,-0.023399,0.031589,0.033100,0.035219,-0.005818,...,-0.001373,0.016570,-0.007297,0.007860,0.002745,0.005276,-0.012483,-0.010073,0.001482,-0.010843
20100105,-0.000428,0.010821,0.003326,0.003005,-0.004218,-0.038773,-0.050127,-0.028553,-0.025959,-0.028231,...,-0.039087,0.015380,0.009606,0.021653,-0.023494,-0.034024,-0.001280,0.043623,0.067963,-0.006623
20100106,-0.013265,0.005874,0.031347,0.049602,0.014701,-0.011657,0.004760,-0.032544,0.045974,-0.029054,...,-0.028566,-0.014088,0.004907,-0.005418,-0.065533,-0.013574,0.008899,-0.001302,-0.003145,-0.008825
20100107,-0.009135,-0.001677,0.010252,0.034320,0.004386,-0.018578,-0.038634,0.014675,0.000596,0.002982,...,0.011445,-0.013702,0.016925,-0.006568,-0.015381,-0.001518,0.014695,0.002608,-0.004632,-0.005260
20100108,-0.009778,-0.015895,0.010192,0.057198,0.002989,0.001229,0.013632,-0.015382,0.002770,-0.011214,...,-0.031061,0.059489,-0.011811,-0.004486,-0.022941,0.002475,-0.002456,0.000755,-0.007476,-0.005746

## crawling data 전처리

In [17]:
def preprocessing(document): #특수문자 기본 전처리 함수
    docu = []
    for doc in document:
        doc = re.sub('[^가-힣0-9\s.]','',doc)
        doc = re.sub('[-=+,#/\?:^$@*\"※~&%ㆍ!』\\‘|\(\)\[\]\<\>`\'…》]','',doc)
#         doc = re.sub('[0-9]+','num',doc) #숫자를 special token num으로 치환
        pattern = re.compile(r'\s+') #중복띄어쓰기 제거
        doc = re.sub(pattern,' ',doc)
        doc = doc.replace('\xa0','') 
        doc = doc.replace('\n','')
        docu.append(doc)

    return docu

In [18]:
nan_idx = [x for x in df[df.str.isnull() ==True].index]
df = df.drop(nan_idx,axis=0) #str 결측치 삭제
df.rmk = df.rmk.fillna('nan')
df = df.reset_index(drop=True)

str_ls = [x for x in df['str']]
corrected_ls = preprocessing(str_ls)
df['str'] = corrected_ls

크롤링한 LV1 data(kospi200 한 번이라도 편입되었던 309개 기업의 텍스트)에 대한 토큰화 이전 기본 전처리를 하고 결측치 처리해주었다.

종목코드는 같지만 거래소에 공시되어 있는 기업의 이름과 dart에서 크롤링한 기업의 이름이 상충되는 것이 있어서 이를 거래소 이름으로 통일하여 주었다. 여기서 지수 편입 퇴출 효과를 제거하기 위해 10년동안 한번도 퇴출된 적이 없었던 113개의 기업들로 데이터를 다시 구성하였다.

In [19]:
change_dic = {'케이씨씨':'KCC',
 '케이티':'KT',
'케이티앤지':'KT&G',
'포스코':'POSCO',
'금호석유화학':'금호석유',
 '기아자동차':'기아차',
'롯데칠성음료':'롯데칠성',
 '삼성화재해상보험':'삼성화재',
 '쌍용양회공업': '쌍용양회',
'아모레퍼시픽그룹':'아모레G',
 '한국단자공업':'한국단자',
'한국전력공사':'한국전력',
'현대엘리베이터':'현대엘리베이',
 '현대자동차':'현대차'}


new_crp_ls = []
for i in df.crp_nm:
    for x in change_dic.keys():
        if i == x:
            i = change_dic[x]
    new_crp_ls.append(i)

df.crp_nm = new_crp_ls

symbols = df_boolean.iloc[0,:] 
con_ls = [df[df.crp_nm == i] for i in symbols]
df_all = pd.concat(x for x in con_ls).reset_index(drop=True) #10년동안 편입되어있던 113개의 기업