In [1]:
import pandas as pd
import matplotlib as plt

In [3]:
cp = pd.read_csv('./data/kospi/preprocessed/df_kospi200_price_return.csv',index_col = 0)
symbols = [x for x in cp.iloc[0,:]][1:]
len(symbols)

313

In [4]:
cp

,Symbol,000020,000030,000050,000070,000080,000100,000120,000140,000150,...,214320,241560,251270,267250,271560,282330,285130,294870,298040,316140
0,Symbol Name,동화약품,우리은행,경방,삼양홀딩스,하이트진로,유한양행,CJ대한통운,하이트진로홀딩스,두산,...,이노션,두산밥캣,넷마블,현대중공업지주,오리온,BGF리테일,SK케미칼,HDC현대산업개발,효성중공업,우리금융지주
1,20100104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20100105,-0.26595744680850686,NaN,0.3830259046467166,-0.5589354429563431,0.6257822277847325,0.5681617173625364,-0.18348623853210455,-2.253032928942811,-0.215586502410281,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20100106,-2.0000000000000018,NaN,2.6709508986846098,-0.7847460924833016,-2.6119402985074647,1.1292002026228376,3.6764705882353033,1.773049645390068,5.501952522175557,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20100107,-1.904761904761909,NaN,-0.371638141809294,-1.5840850655859162,-3.9591315453384457,-0.8383133552709365,0.35460992907800915,-0.5226480836236891,2.761418995408227,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2462,20191223,0.12285,0,0,0.936037,0.724638,0.828316,-1.30293,-0.772201,0.70922,...,0.574713,0.141044,3.02691,1.12518,1.90476,1.53374,0.991736,0,1.14943,1.25
2463,20191224,0,0,-1.35417,1.5456,1.07914,-0.616026,-0.990099,-0.77821,0,...,0,-0.422535,-0.217628,-0.417246,0.934579,0,3.27332,-0.576596,-0.94697,-0.823045
2464,20191226,-1.84049,0,0.95037,1.21766,-0.711744,1.65277,0,-0.784314,1.40845,...,0.142857,0.424328,-1.41767,0.558659,-1.85185,0,-1.42631,0.57994,0.191205,1.65975
2465,20191227,1.75,0,-1.56904,-0.300752,3.04659,0.424628,3,3.55731,-2.36111,...,-0.998573,-0.985915,-0.221239,-4.72222,0,1.81269,1.28617,-0.962376,0.381679,-4.89796
2466,20191230,2.08845,0,-1.38151,1.05581,0.869565,0,0.323625,0.763359,0,...,2.16138,-2.27596,2.43902,-1.45773,-0.471698,0.593472,1.5873,-0.38534,1.3308,-0.429185

In [13]:
df = pd.read_csv('./data/crawling/raw/df_Full.csv',index_col=0)
df_com = pd.read_csv('./data/crawling/preprocessed/df_com.csv',index_col = 0)

In [7]:
df.tail()

,crp_cls,crp_nm,crp_cd,rpt_nm,rcp_no,flr_nm,rcp_dt,rmk,str
2557,Y,SK케미칼,285130.0,사업보고서 (2017.12),2.018033e+13,SK케미칼,20180330.0,정연,나. 영업실적<사업부문별 영업실적>\r다. 신규사업의 개요 SK케미칼은 지속적으로 ...
2558,Y,HDC현대산업개발,294870.0,[기재정정]사업보고서 (2018.12),2.019081e+13,HDC현대산업개발,20190814.0,연,3. 재무현황 및 영업실적가. 연결재무상태표 ...
2559,Y,HDC현대산업개발,294870.0,사업보고서 (2018.12),2.019040e+13,HDC현대산업개발,20190401.0,정연,3. 재무현황 및 영업실적가. 연결재무상태표 ...
2560,Y,효성중공업,298040.0,[기재정정]사업보고서 (2018.12),2.019062e+13,효성중공업,20190618.0,연,"2018년 세계경제는 미중 통상마찰 심화, 미국 기준금리 인상 등의 여파로 중국, ..."
2561,Y,효성중공업,298040.0,사업보고서 (2018.12),2.019033e+13,효성중공업,20190325.0,정연,"2018년 세계경제는 미중 통상마찰 심화, 미국 기준금리 인상 등의 여파로 중국, ..."

In [31]:
deleted_정 = df[df.rmk != '정'].reset_index()
deleted_정연 = df[df.rmk != '정연'].reset_index()
deleted_df = deleted_정[deleted_정.rmk != '정연'].reset_index()
df = deleted_df.iloc[:,2:]
df.rmk = df.rmk.fillna('연') #결측값으로 뽑힌 애들을 '연'으로 정리

사업보고서의 기재정정 부분이 있는 rmk가 '정'과 '정연'인 문서들을 없애주어 같은 연도에 겹치는 사업보고서가 없도록 합니다.

나머지 column의 결측치를 확인 후 처리해줍니다.

In [32]:
df.isnull().sum()

crp_cls    14
crp_nm     14
crp_cd     14
rpt_nm     14
rcp_no     14
flr_nm     14
rcp_dt     14
rmk         0
str        18
dtype: int64

In [33]:
nan_idx = [x for x in df[df.str.isnull() ==True].index]
df.iloc[1990:1993,:]
df = df.drop([282, 283, 284, 286, 287, 288, 290, 291, 292, 293, 294, 295, 786, 1079, 1082, 1083, 1084, 1991],axis=0)
df = df.reset_index(drop=True)

확인결과 '아진카이텍'의 2017,2014,2013,2012년의 사업보고서 텍스트가 뽑히지않았고 나머지 결측치들은 이유를모르는 것들이였다.
따라서 str이 공백인 행들을 모두 제거하였다.

In [ ]:
rcp_ls = df['rcp_no']  #연도 column 생성
rcp_ls = list(map(str,rcp_ls))
rcp__ls = []
for i in rcp_ls:
    rcp__ls.append(int(i[0:4]))
df.insert(0,'연도',rcp__ls)

In [27]:
extract_ls = [x for x in df_com.crp_nm.unique()]

In [150]:
crp_ls = [x for x in cp.columns][1:]

In [142]:
symbols

['동화약품',
 '우리은행',
 '경방',
 '삼양홀딩스',
 '하이트진로',
 '유한양행',
 'CJ대한통운',
 '하이트진로홀딩스',
 '두산',
 '대림산업',
 '일동홀딩스',
 '한국테크놀로지그룹',
 '기아차',
 '대원강업',
 '조선내화',
 '동아쏘시오홀딩스',
 'SK하이닉스',
 '영풍',
 '유수홀딩스',
 '현대건설',
 '삼성화재',
 '삼성물산',
 '한화',
 'DB하이텍',
 'CJ',
 'JW중외제약',
 'LG상사',
 '대한제분',
 '금호전기',
 '동국제강',
 '제일모직',
 '세아베스틸',
 '대한전선',
 '현대해상',
 '동양',
 '종근당홀딩스',
 '대상',
 'SK네트웍스',
 '알루코',
 '대한제당',
 '오리온홀딩스',
 'KISCO홀딩스',
 '코오롱',
 '아세아',
 '고려제강',
 '롯데푸드',
 '한국제지',
 '넥센타이어',
 'KCC',
 '한독',
 '제일파마홀딩스',
 '아모레G',
 '한국쉘석유',
 '금호산업',
 '부광약품',
 '세아제강지주',
 '일성신약',
 '알앤엘바이오',
 '일신방직',
 '태광산업',
 '한일홀딩스',
 '쌍용양회',
 '현대증권',
 '한진중공업홀딩스',
 '대한항공',
 '영진약품',
 'LG',
 'S&T중공업',
 'SK',
 '쌍용차',
 '유니온스틸',
 '보령제약',
 '남양유업',
 '삼양제넥스',
 '롯데정밀화학',
 '현대제철',
 '대덕GDS',
 '한솔홀딩스',
 '신세계',
 '농심',
 '송원산업',
 '세방전지',
 '조광피혁',
 '한솔테크닉스',
 '효성',
 '동일산업',
 '외환은행',
 '롯데지주',
 '삼광글라스',
 '빙그레',
 '녹십자홀딩스',
 '대구은행',
 '부산은행',
 '롯데칠성',
 '현대차',
 '현대그린푸드',
 'POSCO',
 '삼진제약',
 'SPC삼립',
 '삼영전자',
 '파미셀',
 '크라운해태홀딩스',
 'DB손해보험',
 '에스엘',
 '삼성전자',
 'NH투자증권',
 '이수화학',
 'SK디스커버리',
 'LS',
 '녹십자',
 'GS건설',
 '카프로',
 '한일현대시멘트',
 '삼성SDI',
 '대한유화',
 '미래에셋대우',
 'AK홀딩스',
 'GS리테일',
 '벽산',
 '오뚜기',
 '디티알오토모티브',
 '일양약품',
 '국도화학',
 '코리아써키트',
 '서연',
 '도레이케미칼',
 '사조동아원',
 '대덕전자',
 '한국기술산업',
 '서흥',
 '메리츠종금증권',
 '율촌화학',
 '호텔신라',
 '한미사이언스',
 '삼성전기',
 '무림페이퍼',
 '한샘',
 '광동제약',
 '한올바이오파마',
 'KC그린홀딩스',
 '한국조선해양',
 '무림P&P',
 '모토닉',
 '전기초자',
 '한화솔루션',
 'OCI',
 'LS산전',
 '고려아연',
 '삼성중공업',
 '현대하이스코',
 '현대미포조선',
 '화신',
 '아이에스동서',
 'S-Oil',
 'LG이노텍',
 '롯데케미칼',
 '현대상선',
 '현대위아',
 '케이씨오에너지',
 '금호석유',
 'SKC',
 'STX',
 '신성이엔지',
 '현대모비스',
 '한화에어로스페이스',
 'HDC',
 '에스원',
 '디와이',
 '한솔케미칼',
 '동원시스템즈',
 '유니드',
 '인디에프',
 '큐로',
 '한국전력',
 '삼성증권',
 '동부제철',
 '퍼시스',
 'SK텔레콤',
 '현대엘리베이',
 '광전자',
 '한국카본',
 '애경산업',
 '삼성에스디에스',
 '한온시스템',
 '대교',
 '한섬',
 '일진머티리얼즈',
 '일진디스플',
 '코웨이',
 '롯데쇼핑',
 '기업은행',
 'KPX케미칼',
 '한국단자',
 '한화화인케미칼',
 '남해화학',
 '동서',
 'BGF',
 '세하',
 '삼성엔지니어링',
 '삼성물산',
 '팬오션',
 '신도리코',
 '삼성카드',
 '제일기획',
 'KT',
 '신세계인터내셔날',
 'LG유플러스',
 '삼성생명',
 '자화전자',
 '세종공업',
 'KT&G',
 '무학',
 '두산중공업',
 'SBS',
 'LG디스플레이',
 'SK',
 '강원랜드',
 'NAVER',
 '카카오',
 '한국가스공사',
 '엔씨소프트',
 '팜스코',
 '미래에셋증권',
 '대우조선해양',
 '두산인프라코어',
 '한미반도체',
 '코스맥스비티아이',
 '대우건설',
 '포스코인터내셔널',
 '한국항공우주',
 '동원F&B',
 '포스코플랜텍',
 '한전KPS',
 'LG생활건강',
 'LG화학',
 '한전기술',
 '우리금융',
 '신한지주',
 '현대홈쇼핑',
 '한라홀딩스',
 '현대로템',
 '케이피케미칼',
 'S&T모티브',
 'LG전자',
 'STX조선해양',
 '셀트리온',
 'LG생명과학',
 '휴켐스',
 '대웅제약',
 '현대백화점',
 '한국금융지주',
 '롯데하이마트',
 'STX중공업',
 '금호타이어',
 'STX엔진',
 '에이블씨엔씨',
 'GS',
 'CJ CGV',
 '현대리바트',
 'LIG넥스원',
 '휴비스',
 '휠라홀딩스',
 'HSD엔진',
 '대한제강',
 'TBH글로벌',
 '엔케이',
 '현대글로비스',
 '하나금융지주',
 '한화생명',
 '아모레퍼시픽',
 '세원셀론텍',
 'LF',
 '후성',
 'JW홀딩스',
 'SK이노베이션',
 '한진중공업',
 'CJ제일제당',
 'S&TC',
 '웅진에너지',
 '풍산',
 '하이트맥주',
 '일진전기',
 '한국철강',
 'KB금융',
 '한세실업',
 'LG하우시스',
 '영원무역',
 'GKL',
 '락앤락',
 '코오롱인더',
 '한미약품',
 'BNK금융지주',
 'DGB금융지주',
 '이마트',
 '삼양사',
 '한국타이어앤테크놀로지',
 '한국콜마',
 '동아에스티',
 '종근당',
 '쿠쿠홀딩스',
 '코스맥스',
 '만도',
 '삼성바이오로직스',
 '이노션',
 '두산밥캣',
 '넷마블',
 '현대중공업지주',
 '오리온',
 'BGF리테일',
 'SK케미칼',
 'HDC현대산업개발',
 '효성중공업',
 '우리금융지주']

In [55]:
extract_ls[40:50]

['영진약품',
 'LG',
 'S&T중공업',
 '쌍용자동차',
 '유니온스틸',
 '보령제약',
 '남양유업',
 '삼양제넥스',
 '롯데정밀화학',
 '현대제철']

In [135]:
symbols[305:310]

['넷마블', '현대중공업지주', '오리온', 'BGF리테일', 'SK케미칼']

In [139]:
a1 = f[f.crp_nm == '대림산업'] #두산 다음에
a2 = f[f.crp_nm == '기아차'] #한국테크놀로지그룹 다음 .. 안뽑힘
a3 = f[f.crp_nm == '동아쏘시오홀딩스']  #조선내화 , sk하이닉스 전
a4 = f[f.crp_nm == 'JW중외제약']
a5 = f[f.crp_nm == '세아제강지주']
a6 = f[f.crp_nm == '태광산업']
a7 = f[f.crp_nm == '한국조선해양']
a8 = f[f.crp_nm == '대우조선해양']
a9 = f[f.crp_nm == '한전기술']
a10 = f[f.crp_nm == '신한지주']
a11 = f[f.crp_nm == '후성']
a12 = f[f.crp_nm == '한진중공업'] #275:280

In [141]:
df_com[109:112]

,crp_cls,crp_nm,crp_cd,rpt_nm,rcp_no,flr_nm,rcp_dt,rmk,str
109,Y,두산,150.0,사업보고서 (2009.12),2.010033e+13,두산,20100331.0,정연,2010년 들어 세계경제는 부분적으로 회복의 기미가 보이고 있지만 아직 금융시장의 ...
110,Y,일동홀딩스,230.0,사업보고서 (2018.12),2.019040e+13,일동홀딩스,20190401.0,연,2. 개요지난 회기 일동홀딩스는 매출액과 영업이익 모두 적지 않은 성장을 보이며 경...
111,Y,일동홀딩스,230.0,사업보고서 (2017.12),2.018040e+13,일동홀딩스,20180402.0,연,"2. 개요 금년 일동홀딩스와 각 사업회사, 즉 일동그룹의 경영방침은 [고객가치중심의..."

In [140]:
df_com[df_com.crp_nm == '두산']

,crp_cls,crp_nm,crp_cd,rpt_nm,rcp_no,flr_nm,rcp_dt,rmk,str
96,Y,두산,150.0,사업보고서 (2018.12),2.019033e+13,두산,20190329.0,연,2. 개요(주)두산'18년 (주)두산은 다양한 변수가 사업환경에 영향을 미친 가운데...
97,Y,두산,150.0,사업보고서 (2017.12),2.018033e+13,두산,20180330.0,연,"당사가 동 사업보고서에서 미래에 발생할 것으로 예상ㆍ예측한 활동, 사건 또는 현상은..."
98,Y,두산,150.0,사업보고서 (2016.12),2.017033e+13,두산,20170331.0,연,"당사가 동 사업보고서에서 미래에 발생할 것으로 예상ㆍ예측한 활동, 사건 또는 현상은..."
99,Y,두산,150.0,사업보고서 (2015.12),2.016033e+13,두산,20160330.0,연,"당사가 동 사업보고서에서 미래에 발생할 것으로 예상ㆍ예측한 활동, 사건 또는 현상은..."
100,Y,두산,150.0,[기재정정]사업보고서 (2014.12),2.015052e+13,두산,20150515.0,연,주력사업부문인 전자BG는 전자제품의 회로형성에 필수적 소재인 동박적층판과 차세대 디...
101,Y,두산,150.0,[기재정정]사업보고서 (2014.12),2.015042e+13,두산,20150417.0,정연,주력사업부문인 전자BG는 전자제품의 회로형성에 필수적 소재인 동박적층판과 차세대 디...
102,Y,두산,150.0,사업보고서 (2014.12),2.015033e+13,두산,20150331.0,정연,주력사업부문인 전자BG는 전자제품의 회로형성에 필수적 소재인 동박적층판과 차세대 디...
103,Y,두산,150.0,[기재정정]사업보고서 (2013.12),2.014052e+13,두산,20140515.0,연,'13년도 ㈜두산은 양적완화 축소 우려 및 엔저현상 등 불확실한 대외환경에도 불구하...
104,Y,두산,150.0,사업보고서 (2013.12),2.014033e+13,두산,20140331.0,정연,'13년도 ㈜두산은 양적완화 축소 우려 및 엔저현상 등 불확실한 대외환경에도 불구하...
105,Y,두산,150.0,사업보고서 (2012.12),2.013033e+13,두산,20130329.0,연,"2012년 매출은 3조 8,338억원으로써 전년 3조 8,844억원 대비 1.3% ..."
106,Y,두산,150.0,사업보고서 (2011.12),2.012033e+13,두산,20120330.0,연,"2011년 매출은 4조 333억원으로써 전년 3조 7,526억원 대비 7.5% 증가..."
107,Y,두산,150.0,사업보고서 (2010.12),2.011033e+13,두산,20110331.0,연,IT산업의 성장에 따라 전자BG 매출 호조 및 모트롤 합병으로 사업부문 영업이익은 ...
108,Y,두산,150.0,[기재정정]사업보고서 (2009.12),2.010040e+13,두산,20100401.0,연,2010년 들어 세계경제는 부분적으로 회복의 기미가 보이고 있지만 아직 금융시장의 ...
109,Y,두산,150.0,사업보고서 (2009.12),2.010033e+13,두산,20100331.0,정연,2010년 들어 세계경제는 부분적으로 회복의 기미가 보이고 있지만 아직 금융시장의 ...

In [137]:
a3 = f[f.crp_nm == '넷마블']
a3

Empty DataFrame
Columns: [crp_nm, rpt_nm]
Index: []

In [37]:
df.연도.value_counts()

2018    276
2019    273
2017    262
2015    249
2016    243
2014    231
2013    208
2012    154
2011     89
2010     37
2020      2
2009      1
Name: 연도, dtype: int64

In [39]:
df[df.crp_nm == '대우조선해양']

,연도,crp_cls,crp_nm,crp_cd,rpt_nm,rcp_no,flr_nm,rcp_dt,rmk,str
1500,2019,Y,대우조선해양,42660.0,사업보고서 (2018.12),2.019033e+13,대우조선해양,20190329.0,연,"당사가 동 사업보고서에서 미래에 발생할 것으로 예상·예측한 활동, 사건 또는 현상은..."
1501,2018,Y,대우조선해양,42660.0,[기재정정]사업보고서 (2017.12),2.018052e+13,대우조선해양,20180523.0,연,"당사가 동 사업보고서에서 미래에 발생할 것으로 예상·예측한 활동, 사건 또는 현상은..."
1502,2017,Y,대우조선해양,42660.0,[기재정정]사업보고서 (2016.12),2.017102e+13,대우조선해양,20171019.0,연,"당사가 동 사업보고서에서 미래에 발생할 것으로 예상·예측한 활동, 사건 또는 현상은..."
1503,2017,Y,대우조선해양,42660.0,[기재정정]사업보고서 (2015.12),2.017102e+13,대우조선해양,20171019.0,연,"당사가 동 사업보고서에서 미래에 발생할 것으로 예상·예측한 활동, 사건 또는 현상은..."
1504,2017,Y,대우조선해양,42660.0,[기재정정]사업보고서 (2014.12),2.017051e+13,대우조선해양,20170511.0,연,"당사가 동 사업보고서에서 미래에 발생할 것으로 예상 ·예측한 활동, 사건 또는 현상..."
1505,2017,Y,대우조선해양,42660.0,[기재정정]사업보고서 (2013.12),2.017051e+13,대우조선해양,20170511.0,연,"당사가 동 사업보고서에서 미래에 발생할 것으로 예상 ·예측한 활동, 사건 또는 현상..."
1506,2017,Y,대우조선해양,42660.0,[기재정정]사업보고서 (2012.12),2.017051e+13,대우조선해양,20170511.0,연,1. 수주 세계 1위 달성총 143억 달러를 수주하여 3년 연속 100억 달러 이상...

# 2010년부터 크롤링해도 제대로 다 안뽑히는 기업 왜 그런지 찾아봐야한다
# rmk= NaN 인거 적용이안됐음

In [4]:
df_part1 = pd.read_csv('./data/crawling/preprocessed/df_raw1.csv',index_col=0) 
df_part3 = pd.read_csv('./data/crawling/preprocessed/df_part3.csv',index_col=0) 
df_part2 = pd.read_csv('./data/crawling/preprocessed/df_part2.csv',index_col=0)

In [21]:
df_part3.head()

,crp_cls,crp_nm,crp_cd,rpt_nm,rcp_no,flr_nm,rcp_dt,rmk,str
0,E,유니온스틸,140380,사업보고서 (2013.12),20140331002658,유니온스틸,20140331,연,2. 재무상태 및 영업실적가. 재무상태연결실체의 지난 2사업년도 재무상태에 관한 자...
1,E,유니온스틸,140380,사업보고서 (2012.12),20130401001124,유니온스틸,20130401,연,2. 재무상태 및 영업실적가. 재무상태 ...
2,E,유니온스틸,140380,사업보고서 (2011.12),20120330002358,유니온스틸,20120330,연,2. 재무상태 및 영업실적지배회사 유니온스틸(주)은 철강제조기업으로사업내용의 구성은...
3,E,유니온스틸,140380,[첨부추가]사업보고서 (2010.12),20110331000734,유니온스틸,20110331,연,"가. 재무상태2010년말 유동자산은 전년대비 877억원 증가한 6,777억원이며, ..."
4,E,유니온스틸,140380,[첨부추가]사업보고서 (2009.12),20100331002437,유니온스틸,20100331,연,나. 영업실적당사는 2009년 매출액 1조 3천억원과 영업손실 896억원의 영업실적...

In [19]:
len(df_part3.crp_nm.unique())

49

In [208]:
df3.crp_nm.unique()

array(['현대미포조선', '화신', '아이에스동서', 'S-Oil', 'LG이노텍', '롯데케미칼', '현대상선'],
      dtype=object)

In [24]:
sym = pd.DataFrame(symbols, columns = {'Symbol'})
sym[sym.Symbol == '코리아써키트']

     Symbol
123  코리아써키트

In [202]:
df_part3 = pd.concat([df2,df3],ignore_index=True)
df_part3.to_csv('./data/crawling/preprocessed/df_part3.csv')

In [201]:
df_part3 #70~123의 601개

,crp_cls,crp_nm,crp_cd,rpt_nm,rcp_no,flr_nm,rcp_dt,rmk,str
0,E,유니온스틸,140380,사업보고서 (2013.12),20140331002658,유니온스틸,20140331,연,2. 재무상태 및 영업실적가. 재무상태연결실체의 지난 2사업년도 재무상태에 관한 자...
1,E,유니온스틸,140380,사업보고서 (2012.12),20130401001124,유니온스틸,20130401,연,2. 재무상태 및 영업실적가. 재무상태 ...
2,E,유니온스틸,140380,사업보고서 (2011.12),20120330002358,유니온스틸,20120330,연,2. 재무상태 및 영업실적지배회사 유니온스틸(주)은 철강제조기업으로사업내용의 구성은...
3,E,유니온스틸,140380,[첨부추가]사업보고서 (2010.12),20110331000734,유니온스틸,20110331,연,"가. 재무상태2010년말 유동자산은 전년대비 877억원 증가한 6,777억원이며, ..."
4,E,유니온스틸,140380,[첨부추가]사업보고서 (2009.12),20100331002437,유니온스틸,20100331,연,나. 영업실적당사는 2009년 매출액 1조 3천억원과 영업손실 896억원의 영업실적...
...,...,...,...,...,...,...,...,...,...
596,Y,코리아써키트,7810,사업보고서 (2012.12),20130329001106,코리아써키트,20130329,정연,2. 개요2012년도 2분기부터 공급한 Galaxy 시리즈의 물량 호조 등스마트폰 ...
597,Y,코리아써키트,7810,[기재정정]사업보고서 (2011.12),20120515000508,코리아써키트,20120515,연,2. 개요2011년은 신규고객사 확보를 통해 매출처 다변화와 고부가가치 제품 증가 ...
598,Y,코리아써키트,7810,[첨부추가]사업보고서 (2011.12),20120330002173,코리아써키트,20120330,정연,2. 개요2011년은 신규고객사 확보를 통해 매출처 다변화와 고부가가치 제품 증가 ...
599,Y,코리아써키트,7810,[첨부추가]사업보고서 (2010.12),20110331001842,코리아써키트,20110331,연,2. 개요2010년은 신규고객사 매출증가에 따라 매출액이 전년대비 약 14% 증가한...
600,Y,코리아써키트,7810,[첨부추가]사업보고서 (2009.12),20100331001405,코리아써키트,20100331,연,"2. 개요 2009년은 완만한 경기회복과 더불어 고객의 주문량 감소, 판가인하, 국..."